### ISSUE TITLE
more than "#include" does'nt appear

### ISSUE THREAD

**Issue by SebCanet** [BlocklyDuino/BlocklyDuinoReboot#2]
In code generator file, if it's written:
Blockly.Arduino.definitions_['define_servo'] = '#include <Servo.....

in Arduino tab, there's only:
'#include'

but if it's "Blockly.Arduino.definitions_['var_servo' + dropdown_pin] = 'Servo servo_......."
in Arduino tab it's all ok.

**Comment by philippejadin** [comment]
seems to be related to the specific caracter used
<Servo> is converted to an html tag and so disapears. It must be escaped, but how ?

**Comment by philippejadin** [comment]
This is fixed here : https://github.com/philippejadin/BlocklyDuino/commit/7f8ab6afaba65a0de5bd6085666fca12511677bd

In short code has to be escaped before being pretified else it is considered as an html tag

pfiou...

**Comment by SebCanet** [comment]
Great! Thanks a lot.
